name: .NET Release

on:
  release:
    types: [published]
jobs:
  release:
    environment: nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --configuration Release
    - name: Pack
      run: dotnet pack Boyd.NMEA --configuration Release
    - name: Push
      run: dotnet nuget push Boyd.NMEA/bin/Release/Boyd.NMEA.${{ github.event.tag_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
